version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    environment:
      - ORACLE_PASSWORD=syspassword
      - APP_USER=hr
      - APP_USER_PASSWORD=hr
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus appuser/userpassword@localhost:1521/XE"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "1050:1050"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//localhost:1521/orclpdb
      - SPRING_DATASOURCE_USERNAME=hr
      - SPRING_DATASOURCE_PASSWORD=hr
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "7700:7700"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  oracle-data: